### ISSUE TITLE
Fire beaver damn freeze

### ISSUE THREAD

**Issue by headsupduse** [tobiaspfaff/grim_mouse#30]
This is my 1st time playing the game. When I went through the door in the forest that leads to the fire beaver damn, after the CG cutscene, the beaver runs away from Manny, all the way to the opposite side of the damn from where Manny was, and then stops, locked in a running animation. The cursor was in the X shape, and I couldn't move Manny around or do anything. From what I understand, the beaver is supposed to run towards Manny and chase him out. This is halting my progress. Thanks for all of your work!

**Comment by frankiesimon** [comment]
I got to the same point exactly in the game.

Thank you for all the amazing work up to this point!

**Comment by frankiesimon** [comment]
Update: I didn't get a freeze when I picked up the key before going through the door. I did get some freezes after the second or third time the beavers chased me out - but anyway, I got through the first freeze by picking up the key first.

**Comment by ZydrateJunkie** [comment]
Exacty the same issue. Cannot resolve it and resume the game from where I left off, :(.

**Comment by absolutltegend** [comment]
This is happening to me as well.

Its like the cursor is waiting for the scene to load (it displays the 'X' symbol). The other keys are useless at this time, and you cannot access the developer console either.

Tobias great work with what you have accomplished with this interface. It is seamless and despite the minimal bugs I think it is fantastic!

**Comment by Pg32312** [comment]
I am also experiencing this bug.  No matter how many times i try and load into that zone, or have gotten the key first before going in there - the cursor freezes on an 'X' and will not allow any action once the beaver cut-scene ends.

**Comment by tobiaspfaff** [comment]
fixed in git

**Comment by tobiaspfaff** [comment]
in v0.5

**Comment by tahuomo** [comment]
The bug still occurs in v0.5_git if you have not completed the bone wagon upgrade.
